import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/authContext";
import { ToastProvider } from "@/context/ToastContext";

export const metadata: Metadata = {
  title: "Lief",
  description: "Generated by create next app",
  icons: {
    icon: '/Logo.svg?v=12', 
  }
};


const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="winter">
      <head>
        <link rel="icon" href="/Logo.svg?v='12" type="image/svg+xml" />
      </head>
      <body className={`${inter.className} antialiased`}>
        <AuthProvider>
          <ToastProvider>{children}</ToastProvider>
        </AuthProvider>
      </body>
    </html>

  );
}
